public enum MessageType {
    APPEND,// FROM THE CLIENT TO MS
    READ,// FROM THE CLIENT TO MS--
    CREATE,// FROM THE CLIENT TO MS --
    HEARTBEAT,// FROM THE SERVER TO MS
    READRESPONSE,// FROM THE MS TO CLIENT
    APPENDRESPONSE,// FROM THE MS TO CLIENT
    CREATERESPONSE,// FROM THE MS TO CLIENT
    COMMITREQUEST,//2 PHASE 2 COMMIT INITIATION FROM CLIENT TO SERVER
    AGREED,// SERVER TO CLIENT 2 PHASE 2 COMMIT 
    ABORT,// SERVER TO CLIENT 2 PHASE 2 COMMIT 
    COMMIT,// CLIENT TO SERVER 2 PHASE 2 COMMIT 
    READFILE,// CLIENT TO SERVER --
    READFILERESPONSE,// SERVER TO CLIENT
    UPDATEREPLICA,// FROM  MSERVER TO SERVER
   CREATECOMMAND,// MS TO SERVER FOR NEW FILE CREATION--
   APPENDCOMPLETE,// FROM CLIENT TO METADATASERVER TELLING THAT WRITE IS COMPLETE
    APPENDNOTCOMPLETE // FROM CLIENT TO METADATASERVER TELLING THAT WRITE IS INCOMPLETE
}
